_target_: pytorch_lightning.Trainer

gpus: 1

min_epochs: 10
max_epochs: 10000

# plugins: "ddp_sharded"

gradient_clip_val: 0.5
gradient_clip_algorithm: "value"

weights_summary: "full"
progress_bar_refresh_rate: 10
resume_from_checkpoint: null
