_target_: src.models.transformer_model.TransformerModel

architecture: gptneo
lr: 0.0001
betas: [0.9, 0.98]
eps: 1e-6
weight_decay: 0.15
n_positions: ${max_seq}
n_embed: 512
n_head: 8
n_layer: 8
gradient_checkpointing: True
