_target_: src.datamodules.sequence_datamodule.SequenceDataModule

data_dir: ${data_dir} # data_dir is specified in config.yaml
batch_size: 2
num_workers: 8
pin_memory: True
num_velocity_bins: ${num_velocity_bins}
steps_per_second: ${steps_per_second}
time_augment: 0.05
transpose_augment: 3
max_seq: ${max_seq}
